"""
Export Engine: generate publication-ready outputs in multiple formats.

Supports: LaTeX, Markdown, CSV, Excel, HTML, JSON.
"""
import dataclasses
import json
import os
from typing import Any, Dict, List, Optional

import pandas as pd

from src.utils import get_logger

logger = get_logger(__name__)


@dataclasses.dataclass
class ExportResult:
    format: str
    path: str
    success: bool
    error: str = ""


def export_results(
    results: Dict[str, Any],
    output_dir: str,
    formats: Optional[List[str]] = None,
    dataset_name: str = "dataset",
) -> List[ExportResult]:
    if formats is None:
        formats = ["csv", "latex", "markdown", "html"]

    os.makedirs(output_dir, exist_ok=True)
    export_list = []
    metrics_data = _extract_metrics_table(results)

    for fmt in formats:
        try:
            if fmt == "csv":
                path = _export_csv(metrics_data, output_dir, dataset_name)
            elif fmt == "latex":
                path = _export_latex(metrics_data, output_dir, dataset_name)
            elif fmt == "markdown":
                path = _export_markdown(metrics_data, output_dir, dataset_name)
            elif fmt == "html":
                path = _export_html(results, metrics_data, output_dir, dataset_name)
            elif fmt == "json":
                path = _export_json(results, output_dir, dataset_name)
            else:
                export_list.append(ExportResult(format=fmt, path="", success=False,
                                                error=f"Unsupported format: {fmt}"))
                continue
            export_list.append(ExportResult(format=fmt, path=path, success=True))
            logger.info("Exported %s to %s", fmt, path)
        except Exception as exc:
            export_list.append(ExportResult(format=fmt, path="", success=False, error=str(exc)))
            logger.error("Failed to export %s: %s", fmt, exc)

    return export_list


def _extract_metrics_table(results: Dict[str, Any]) -> pd.DataFrame:
    rows = []
    if "model_comparison" in results:
        for model_name, metrics in results["model_comparison"].items():
            if isinstance(metrics, dict):
                row = {"Model": model_name}
                row.update(metrics)
                rows.append(row)
    if "eval_df" in results and results["eval_df"] is not None:
        eval_df = results["eval_df"]
        if isinstance(eval_df, pd.DataFrame) and not eval_df.empty:
            return eval_df
    if rows:
        return pd.DataFrame(rows)
    summary = {"Dataset": results.get("dataset", "N/A")}
    if "churn_rate" in results:
        summary["Churn Rate"] = f"{results['churn_rate']:.1%}"
    if "best_model" in results:
        summary["Best Model"] = results["best_model"]
    return pd.DataFrame([summary])


def _export_csv(df: pd.DataFrame, output_dir: str, name: str) -> str:
    path = os.path.join(output_dir, f"{name}_metrics.csv")
    df.to_csv(path, index=False)
    return path


def _export_latex(df: pd.DataFrame, output_dir: str, name: str) -> str:
    path = os.path.join(output_dir, f"{name}_tables.tex")
    with open(path, "w") as f:
        f.write("% Auto-generated by ChurnLab v1.0\n")
        f.write("% Dataset: " + name + "\n\n")
        f.write("\\begin{table}[ht]\n")
        f.write("\\centering\n")
        f.write("\\caption{Model Performance Comparison}\n")
        f.write("\\label{tab:" + name + "_metrics}\n")
        f.write(df.to_latex(index=False, float_format="%.4f"))
        f.write("\\end{table}\n")
    return path


def _export_markdown(df: pd.DataFrame, output_dir: str, name: str) -> str:
    path = os.path.join(output_dir, f"{name}_summary.md")
    with open(path, "w") as f:
        f.write(f"# ChurnLab Report: {name}\n\n")
        f.write("## Model Performance\n\n")
        f.write(df.to_markdown(index=False))
        f.write("\n\n")
    return path


def _export_html(results: Dict, df: pd.DataFrame, output_dir: str, name: str) -> str:
    path = os.path.join(output_dir, f"{name}_report.html")
    churn_rate = results.get("churn_rate", "N/A")
    if isinstance(churn_rate, float):
        churn_rate = f"{churn_rate:.1%}"
    best_model = results.get("best_model", "N/A")

    html = f"""<!DOCTYPE html>
<html><head><title>ChurnLab Report: {name}</title>
<style>
body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
h1 {{ color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }}
h2 {{ color: #16213e; }}
table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
th {{ background-color: #16213e; color: white; }}
tr:nth-child(even) {{ background-color: #f2f2f2; }}
.metric {{ display: inline-block; margin: 10px 20px; padding: 15px; background: #f8f9fa;
           border-radius: 8px; border-left: 4px solid #16213e; }}
.metric-value {{ font-size: 1.5em; font-weight: bold; color: #16213e; }}
.metric-label {{ font-size: 0.85em; color: #666; }}
</style></head><body>
<h1>ChurnLab Report: {name}</h1>
<div>
<div class="metric"><div class="metric-value">{churn_rate}</div><div class="metric-label">Churn Rate</div></div>
<div class="metric"><div class="metric-value">{best_model}</div><div class="metric-label">Best Model</div></div>
</div>
<h2>Model Performance</h2>
{df.to_html(index=False, classes="styled-table")}
<hr><p><em>Generated by ChurnLab v1.0</em></p>
</body></html>"""

    with open(path, "w") as f:
        f.write(html)
    return path


def _export_json(results: Dict, output_dir: str, name: str) -> str:
    path = os.path.join(output_dir, f"{name}_results.json")
    serializable = {}
    for k, v in results.items():
        if isinstance(v, pd.DataFrame):
            serializable[k] = v.to_dict()
        elif isinstance(v, dict):
            serializable[k] = v
        elif isinstance(v, (str, int, float, bool, type(None))):
            serializable[k] = v
    with open(path, "w") as f:
        json.dump(serializable, f, indent=2, default=str)
    return path
