"""
Plugin Scaffolding: generate plugin templates for custom business logic.
"""
import os
from typing import Optional

from src.utils import get_logger

logger = get_logger(__name__)

PLUGIN_TEMPLATE = '''"""
Custom plugin: {plugin_name}

Generated by: churn plugin create
"""
from src.models.base import ModelWrapper
from src.churn.base import ChurnStrategy


class CustomChurnStrategy(ChurnStrategy):
    """Custom churn labeling strategy."""

    @property
    def name(self) -> str:
        return "{plugin_name}"

    @property
    def description(self) -> str:
        return "Custom churn strategy for {plugin_name}"

    @property
    def required_columns(self) -> list:
        return ["customer_id", "event_time"]

    def apply(self, df, **kwargs):
        raise NotImplementedError("Implement your custom churn logic here")


# Register the strategy
# from src.churn.registry import register_strategy
# register_strategy("{plugin_name}", CustomChurnStrategy())
'''

MANIFEST_TEMPLATE = '''"""
Custom dataset adapter: {plugin_name}

Generated by: churn plugin create
"""
from src.datasets.base import BaseDatasetAdapter


class CustomAdapter(BaseDatasetAdapter):
    """Custom dataset adapter for {plugin_name}."""

    @property
    def dataset_name(self) -> str:
        return "{plugin_name}"

    def load_raw_data(self):
        raise NotImplementedError("Implement data loading here")

    def preprocess(self, df):
        return df

    def standardize_schema(self, df):
        return df
'''


def create_plugin(
    plugin_name: str,
    plugin_type: str = "strategy",
    output_dir: Optional[str] = None,
) -> str:
    """Create a plugin template.

    Parameters
    ----------
    plugin_name : str
        Name of the plugin.
    plugin_type : str
        Type of plugin: "strategy", "adapter", or "model".
    output_dir : str, optional
        Directory to create the plugin in.

    Returns
    -------
    Path to the created plugin file.
    """
    if output_dir is None:
        output_dir = os.path.join("plugins", plugin_name)
    os.makedirs(output_dir, exist_ok=True)

    if plugin_type == "strategy":
        content = PLUGIN_TEMPLATE.format(plugin_name=plugin_name)
        filename = f"{plugin_name}_strategy.py"
    elif plugin_type == "adapter":
        content = MANIFEST_TEMPLATE.format(plugin_name=plugin_name)
        filename = f"{plugin_name}_adapter.py"
    else:
        content = PLUGIN_TEMPLATE.format(plugin_name=plugin_name)
        filename = f"{plugin_name}_plugin.py"

    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w") as f:
        f.write(content)

    logger.info("Created plugin template: %s", filepath)
    return filepath
