"""
YAML config generator: produces reusable dataset configs from inspection results.
"""
import dataclasses
import os
from typing import Any, Dict, List, Optional

from src.wizard.inspector import InspectionResult
from src.utils import get_logger

logger = get_logger(__name__)

# ── Default churn strategies by ecosystem ──────────────────────────
_ECOSYSTEM_DEFAULTS = {
    "transactional_marketplace": {
        "churn_strategy": "inactivity",
        "prediction_window_days": 180,
        "justification": "180-day inactivity window for transactional marketplace.",
    },
    "clickstream_commerce": {
        "churn_strategy": "inactivity",
        "prediction_window_days": 90,
        "justification": "90-day inactivity window for clickstream-based commerce.",
    },
    "habitual_retail": {
        "churn_strategy": "cadence",
        "prediction_window_days": 180,
        "justification": "180-day cadence-based window for habitual retail.",
    },
    "subscription": {
        "churn_strategy": "subscription",
        "prediction_window_days": None,
        "justification": "Native churn label from subscription status.",
    },
}


@dataclasses.dataclass
class WizardConfig:
    """Generated configuration for a new dataset."""
    dataset_name: str
    ecosystem_type: str
    source_url: str
    citation: str
    customer_id_col: str
    event_time_col: str
    transaction_value_col: Optional[str] = None
    event_type_col: Optional[str] = None
    churn_strategy: str = "inactivity"
    prediction_window_days: int = 180
    churn_justification: str = ""
    available_feature_groups: List[str] = dataclasses.field(
        default_factory=lambda: ["purchase", "monetary", "inactivity"]
    )
    column_mapping: Dict[str, str] = dataclasses.field(default_factory=dict)
    timestamp_columns: List[str] = dataclasses.field(default_factory=list)
    non_negative_columns: List[str] = dataclasses.field(default_factory=list)
    median_fill: List[str] = dataclasses.field(default_factory=list)
    zero_fill: List[str] = dataclasses.field(default_factory=list)
    warnings: List[str] = dataclasses.field(default_factory=list)

    def to_yaml(self) -> str:
        """Serialize to a Dataset Manifest YAML string."""
        lines = []

        def _add(text: str = "") -> None:
            lines.append(text)

        def _comment(text: str) -> None:
            lines.append(f"# {text}")

        def _yaml_value(val: Any) -> str:
            if val is None:
                return "null"
            if isinstance(val, bool):
                return "true" if val else "false"
            if isinstance(val, str):
                if val in ("true", "false", "null", "yes", "no", "on", "off"):
                    return f"'{val}'"
                if any(c in val for c in ":#{}[]|>&*!%@`"):
                    return f"'{val}'"
                return val
            if isinstance(val, (int, float)):
                return str(val)
            return str(val)

        def _yaml_list(items: List[Any], indent: int = 0) -> None:
            prefix = "  " * indent
            for item in items:
                lines.append(f"{prefix}- {_yaml_value(item)}")

        # ── Header ────────────────────────────────────────────────
        _comment("=" * 70)
        _comment(f"{self.dataset_name.upper()} — Dataset Manifest")
        _comment("=" * 70)
        _comment(f"Ecosystem: {self.ecosystem_type}")
        _comment(f"Churn window: {self.prediction_window_days} days")
        if self.source_url:
            _comment(f"Source: {self.source_url}")
        _comment("Generated by: churn register / churn wizard")
        _comment("")

        # ── Adapter section ───────────────────────────────────────
        _add("adapter:")
        _add("  type: generic")
        _add("  plugin: null")
        _add("")

        # ── Root directory ────────────────────────────────────────
        _add("root_directory: null")
        _add("")

        # ── Dataset section ───────────────────────────────────────
        _add("dataset:")
        _add(f"  name: {self.dataset_name}")
        _add(f"  ecosystem_type: {self.ecosystem_type}")
        if self.citation:
            _add(f"  citation: >")
            _add(f"    {self.citation}")
        if self.source_url:
            _add(f"  source_url: {self.source_url}")
        _add("")

        # ── Churn section ─────────────────────────────────────────
        _add("churn:")
        _add(f"  strategy: {self.churn_strategy}")
        _add(f"  uses_native_churn_label: false")
        if self.prediction_window_days:
            _add(f"  prediction_window_days: {self.prediction_window_days}")
        else:
            _add(f"  prediction_window_days: null")
        if self.churn_justification:
            _add(f"  justification: >")
            _add(f"    {self.churn_justification}")
        _add("")

        # ── Features section ──────────────────────────────────────
        _add("features:")
        _add("  available_groups:")
        _yaml_list(self.available_feature_groups, indent=2)
        _add("")

        # ── Schema section ────────────────────────────────────────
        _add("schema:")
        _add("  version: 2")
        _add("  column_mapping:")
        if self.column_mapping:
            for native, standard in self.column_mapping.items():
                _add(f"    {native}: {standard}")
        else:
            _add("    # Map native column names to standardized schema")
            _add(f"    # {self.customer_id_col}: customer_id")
            _add(f"    # {self.event_time_col}: event_time")
        _add("  synthetic_columns: {}")
        _add("")

        # ── Files section ─────────────────────────────────────────
        _add("files:")
        _add("  required:")
        _add(f"    data: {os.path.basename(self.customer_id_col) if self.customer_id_col else 'data.csv'}")
        # Placeholder — user will fill in actual filename
        _add("  optional: {}")
        _add("")

        # ── Preprocessing section ─────────────────────────────────
        _add("preprocessing:")
        if self.timestamp_columns:
            _add("  timestamp_columns:")
            _yaml_list(self.timestamp_columns, indent=2)
        elif self.event_time_col:
            _add(f"  timestamp_columns:")
            _add(f"    - {self.event_time_col}")

        if self.non_negative_columns:
            _add("  non_negative_columns:")
            _yaml_list(self.non_negative_columns, indent=2)

        if self.median_fill:
            _add("  median_fill:")
            _yaml_list(self.median_fill, indent=2)

        if self.zero_fill:
            _add("  zero_fill:")
            _yaml_list(self.zero_fill, indent=2)

        _add("")

        # ── Warnings ──────────────────────────────────────────────
        if self.warnings:
            _comment("WARNINGS:")
            for w in self.warnings:
                _comment(f"  - {w}")
            _comment("")

        return "\n".join(lines)


def _determine_feature_groups(inspection: InspectionResult) -> List[str]:
    """Determine available feature groups based on detected columns."""
    groups = ["purchase"]  # Always available if we have customer_id + event_time

    if inspection.inferred_transaction_value:
        groups.append("monetary")

    groups.append("inactivity")  # Always available with timestamps

    # Check for review scores
    for col in inspection.columns:
        if col.inferred_role == "review_score":
            groups.append("review")
            break

    # Check for payment type
    for col in inspection.columns:
        if col.inferred_role == "payment_type":
            groups.append("payment")
            break

    return groups


def _build_column_mapping(inspection: InspectionResult) -> Dict[str, str]:
    """Build column mapping from native to standardized names."""
    mapping = {}

    if inspection.inferred_customer_id:
        mapping[inspection.inferred_customer_id] = "customer_id"

    if inspection.inferred_event_time:
        mapping[inspection.inferred_event_time] = "event_time"

    if inspection.inferred_transaction_value:
        mapping[inspection.inferred_transaction_value] = "transaction_value"

    if inspection.inferred_event_type:
        mapping[inspection.inferred_event_type] = "event_type"

    return mapping


def _detect_timestamp_columns(inspection: InspectionResult) -> List[str]:
    """Find all columns that look like timestamps."""
    ts_cols = []
    if inspection.inferred_event_time:
        ts_cols.append(inspection.inferred_event_time)

    for col in inspection.columns:
        if col.is_datetime and col.name not in ts_cols:
            ts_cols.append(col.name)

    return ts_cols


def _detect_non_negative_columns(inspection: InspectionResult) -> List[str]:
    """Find numeric columns that should be non-negative."""
    nn_cols = []
    for col in inspection.columns:
        if col.is_numeric and col.inferred_role in ("transaction_value",):
            nn_cols.append(col.name)
    return nn_cols


def generate_config(
    inspection: InspectionResult,
    dataset_name: Optional[str] = None,
    ecosystem_type: Optional[str] = None,
    source_url: str = "",
    citation: str = "",
    churn_strategy: Optional[str] = None,
    prediction_window_days: Optional[int] = None,
) -> WizardConfig:
    """Generate a dataset configuration from inspection results.

    Parameters
    ----------
    inspection : InspectionResult
        Results from inspect_csv().
    dataset_name : str, optional
        Override the auto-detected dataset name.
    ecosystem_type : str, optional
        Override the auto-detected ecosystem type.
    source_url : str
        URL where the dataset can be obtained.
    citation : str
        How to cite this dataset.
    churn_strategy : str, optional
        Override the default churn strategy.
    prediction_window_days : int, optional
        Override the default prediction window.

    Returns
    -------
    WizardConfig with all settings ready for YAML export.
    """
    name = dataset_name or inspection.suggested_dataset_name

    # Default ecosystem
    eco = ecosystem_type or "transactional_marketplace"

    # Get defaults for ecosystem
    defaults = _ECOSYSTEM_DEFAULTS.get(eco, _ECOSYSTEM_DEFAULTS["transactional_marketplace"])

    strategy = churn_strategy or defaults["churn_strategy"]
    window = prediction_window_days or defaults["prediction_window_days"]
    justification = defaults["justification"]

    # Build config
    config = WizardConfig(
        dataset_name=name,
        ecosystem_type=eco,
        source_url=source_url,
        citation=citation,
        customer_id_col=inspection.inferred_customer_id or "",
        event_time_col=inspection.inferred_event_time or "",
        transaction_value_col=inspection.inferred_transaction_value,
        event_type_col=inspection.inferred_event_type,
        churn_strategy=strategy,
        prediction_window_days=window,
        churn_justification=justification,
        available_feature_groups=_determine_feature_groups(inspection),
        column_mapping=_build_column_mapping(inspection),
        timestamp_columns=_detect_timestamp_columns(inspection),
        non_negative_columns=_detect_non_negative_columns(inspection),
        warnings=list(inspection.warnings),
    )

    logger.info(
        "Generated config for '%s': strategy=%s, window=%s, groups=%s",
        name, strategy, window, config.available_feature_groups,
    )

    return config
